# Generated by Django 6.0 on 2026-01-04 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="location",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="price",
        ),
        migrations.AddField(
            model_name="tour",
            name="city",
            field=models.CharField(default=0.16666666666666666, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="country",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="ticket_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tour",
            name="venue",
            field=models.CharField(default="date", max_length=200),
            preserve_default=False,
        ),
    ]
